import Head from "next/head";

export default function Home({subject}) {
  {console.log(subject)}
  return (
    <div>
      <Head>
        <title>Tutors Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {subject.map(sub=>
          <>
          <h2>{sub.title}</h2>
          </>
        )} */}
      </main>
    </div>
  );
}


export const getStaticProps = async ()=>{
  const res = await fetch('http://127.0.0.1:5000/api/v1/subject')
  const data = await res.json()
console.log(data);
  return{
    props:{
      subject:data
    }
  }
}